// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxgtqbfrfsmanfgylyhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4Z3RxYmZyZnNtYW5mZ3lseWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Njk2NDMsImV4cCI6MjA2MjE0NTY0M30.betzJz8HBvt7-Lr6Jr0OEaYXt1Y9rsAM7I37Ewgjl0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);